### ISSUE TITLE
error when run make sandbox

### ISSUE THREAD

**Issue by muyang** [cage1016/generator-django-oscar-app#1]
I followed the demo, but there was an error when run make sandbox:

...
...
Successfully installed rst2pdf-0.93.dev0
./setup.py develop
running develop
running egg_info
writing requirements to django_oscar_hooks.egg-info/requires.txt
writing django_oscar_hooks.egg-info/PKG-INFO
writing top-level names to django_oscar_hooks.egg-info/top_level.txt
writing dependency_links to django_oscar_hooks.egg-info/dependency_links.txt
reading manifest file 'django_oscar_hooks.egg-info/SOURCES.txt'
writing manifest file 'django_oscar_hooks.egg-info/SOURCES.txt'
running build_ext
Creating /home/hmmm/.virtualenvs/django-oscar-hooks/lib/python2.7/site-packages/django-oscar-hooks.egg-link (link to .)
django-oscar-hooks 0.1.0 is already the active version in easy-install.pth

Installed /home/hmmm/webapp/oscar-app/django-oscar-hooks
Processing dependencies for django-oscar-hooks==0.1.0
****error: Django 1.11.1 is installed but Django<1.11 is required by set(['django-haystack'])****
make: *** [install] Error 1

**Comment by muyang** [comment]
...
...
setup(
    name='django-oscar-demo',
    version=__version__,
    url='https://github.com/muyang/django-oscar-demo.git',
    author='muyang <muyang0828@gmail.com>',
    description=('a demo'),
    long_description=open('README.md').read(),
    keywords='Oscar,django',
    license=open('LICENSE').read(),
    platforms=['linux'],
    packages=find_packages(exclude=['sandbox*', 'tests*']),
    include_package_data=True,
    install_requires=[
        'django>=1.8.8,<1.10',
        'django-oscar>=1.1'
    ],
...
...
I set the django version :+1:     'django>=1.8.8,<1.10',

**now, error became **

rm sandbox/db.sqlite
rm: cannot remove ‘sandbox/db.sqlite’: No such file or directory
make: [sandbox] Error 1 (ignored)
sandbox/manage.py migrate
Traceback (most recent call last):
  File "sandbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/hmmm/.virtualenvs/django-oscar-demo/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/hmmm/.virtualenvs/django-oscar-demo/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/home/hmmm/.virtualenvs/django-oscar-demo/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/hmmm/.virtualenvs/django-oscar-demo/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/hmmm/.virtualenvs/django-oscar-demo/lib/python2.7/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/home/hmmm/.virtualenvs/django-oscar-demo/lib/python2.7/site-packages/debug_toolbar/settings.py", line 228, in patch_all
    patch_root_urlconf()
  File "/home/hmmm/.virtualenvs/django-oscar-demo/lib/python2.7/site-packages/debug_toolbar/settings.py", line 216, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/home/hmmm/.virtualenvs/django-oscar-demo/lib/python2.7/site-packages/django/urls/base.py", line 60, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/hmmm/.virtualenvs/django-oscar-demo/lib/python2.7/site-packages/django/urls/resolvers.py", line 348, in app_dict
    self._populate()
  File "/home/hmmm/.virtualenvs/django-oscar-demo/lib/python2.7/site-packages/django/urls/resolvers.py", line 291, in _populate
    p_pattern = pattern.regex.pattern
AttributeError: 'str' object has no attribute 'regex'
make: *** [sandbox] Error 1

**Comment by muyang** [comment]
remove pattern and ' ', change ( ) to [ ]

urlpatterns = pattern(
    ''
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^checkout/demo1/', include('demo1.urls')),
    url(r'^dashboard/demo1/', include(demo1_dashboard.urls)),
    url(r'^', include(application.urls)),
]

to
urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^checkout/demo1/', include('demo1.urls')),
    url(r'^dashboard/demo1/', include(demo1_dashboard.urls)),
    url(r'^', include(application.urls)),
]

**Comment by muyang** [comment]
then error ''ImportError: No module named south.v2'' came,

add  django-extensions==1.6.7 in requirements.sandbox.txt
or pip install django-extensions==1.6.7

and
change pycountry==1.20 to pycountry==17.5.14

**Comment by muyang** [comment]
new error 

CommandError: No fixture named 'order' found.

change name ~/sandbox/fixtures/orders.json to order.json

**Comment by muyang** [comment]
now server can run:

TemplateDoesNotExist at /
debug_toolbar/base.html
